### ISSUE TITLE
Unable to start container on Fedora 22

### ISSUE THREAD

**Issue by bpradipt** [hyperhq/runv#151]
I'm unable to start a container using runv and qemu on my Fedora 22 system. 
The busybox container rootfs along with config.json and runtime.json is in the current dir.
The qemu instance does get created. Any suggestions on debugging the issue ?
<pre>
# ./runv --kernel ../hyperstart/build/kernel --initrd ../hyperstart/build/hyper-initrd.img start start
tag=qck14w9g
Failed to reset winsize
copy from stdin to remote 0, err write unix @->/run/opencontainer/containers/runv/runv.sock: write: broken pipe
runvRequest failed: dial unix /run/opencontainer/containers/runv/runv.sock: connect: connection refused
start container failed: dial unix /run/opencontainer/containers/runv/runv.sock: connect: connection refused

# ps aux | grep qemu
root     21259 96.0  1.1 793620 93744 ?        Sl   11:41   0:03 qemu-system-x86_64 -machine pc-i440fx-2.0,accel=kvm,usb=off -global kvm-pit.lost_tick_policy=discard -cpu host -kernel /home/pradipta/temp/hyperstart/build/kernel -initrd /home/pradipta/temp/hyperstart/build/hyper-initrd.img -append "console=ttyS0 panic=1 no_timer_check" -realtime mlock=off -no-user-config -nodefaults -no-hpet -rtc base=utc,driftfix=slew -no-reboot -display none -boot strict=on -m 128 -smp 1 -qmp unix:/var/run/hyper/vm-MjoAidCDJo/qmp.sock,server,nowait -serial unix:/var/run/hyper/vm-MjoAidCDJo/console.sock,server,nowait -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x2 -device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x3 -chardev socket,id=charch0,path=/var/run/hyper/vm-MjoAidCDJo/hyper.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charch0,id=channel0,name=sh.hyper.channel.0 -chardev socket,id=charch1,path=/var/run/hyper/vm-MjoAidCDJo/tty.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charch1,id=channel1,name=sh.hyper.channel.1 -fsdev local,id=virtio9p,path=/var/run/hyper/vm-MjoAidCDJo/share_dir,security_model=none -device virtio-9p-pci,fsdev=virtio9p,mount_tag=share_dir

</pre>

**Comment by laijs** [comment]
thanks for report, i will look into it.

**Comment by gao-feng** [comment]
panic on https://github.com/hyperhq/runv/blob/master/hypervisor/vm_states.go#L289

since userPod.Containers is nil

**Comment by bpradipt** [comment]
Any suggestions for debugging this issue ?

**Comment by gao-feng** [comment]
@bpradipt Sorry for late response, you can run runv with the options `runv start -v=3` and found the log in /var/log/hyper/runv-ns-daemon.xxx, since runv may panic, the glog has no chance to flush out logs, you may need to change the glog package in Godep, call Flush() in func (l *loggingT) output(...).

For this problem, please try this patch.

diff --git a/hypervisor/vm_states.go b/hypervisor/vm_states.go
index 3f345c3..9715cdb 100644
--- a/hypervisor/vm_states.go
+++ b/hypervisor/vm_states.go
@@ -107,6 +107,7 @@ func (ctx *VmContext) prepareContainer(cmd *NewContainerCommand) *VmContainer {
                ctx.ptys.attachId++
        }
 
+       ctx.userSpec.Containers = append(ctx.userSpec.Containers, *cmd.container)
        ctx.vmSpec.Containers = append(ctx.vmSpec.Containers, *vmContainer)

**Comment by bpradipt** [comment]
@gao-feng I verified your patch and it works fine. Thanks a lot!!

**Comment by gao-feng** [comment]
@bpradipt You are welcome, thanks for the report
