### ISSUE TITLE
move the code of api between runv and hyperstart into hyperstart/api/json/

### ISSUE THREAD

**Issue by laijs** [hyperhq/runv#213]
the code of api between runv and hyperstart is spread everywhere
- hypervisor/constants.go INIT_XXXX
- hypervisor/events.go the structs sent into hyperstart
- ttyMessage
- WindowSize
- (all structs sent into ctx.vm)
- hypervisor/pod.go the structs VmXXXX
- others ...

after they are moved, they will be referred via hyperstartapi.XXXXX
```go
import hyperstartapi "github.com/hyperhq/runv/hyperstart/api/json"
```

@yaozengzeng

**Comment by YaoZengzeng** [comment]
get it!

**Comment by laijs** [comment]
the following code in `func (ctx *VmContext) setWindowSize(tag string, size *WindowSize)` also needs to be moved.
```go
map[string]interface{}{
			"seq":    session,
			"row":    size.Row,
			"column": size.Column,
		}
```

**Comment by laijs** [comment]
DecodedMessage

**Comment by laijs** [comment]
ref: https://github.com/hyperhq/runv/pull/214
ref: https://github.com/hyperhq/runv/pull/216

**Comment by YaoZengzeng** [comment]
If move the struct DecodedMessage to hyperstartapi would result "imported cycle" because of the "Event" item in it.So my idea is use the struct VmMessage{Message hyperstartapi.DecodedMessage, Event VmEvent} to replace the old DecodedeMessage and put the old one into hyperstartapi.Then everything is fine.

**Comment by laijs** [comment]
TODO: check any leftover works.
